#! /usr/bin/env python

from subprocess import check_output, call
from pprint import pprint
import sys
import re

def yellow(s):
    return "\033[33m%s\033[0m" % s

def remotes():
    result = {}
    remotes = check_output("git config --get-regexp ^remote\.\*\.url", shell=True).rstrip()
    for line in remotes.split('\n'):
        match = re.match('^remote\.(.+?)\.url (.+)$', line)
        if match:
            result[match.group(1)] = match.group(2)
    return result


if __name__ == '__main__':
    for remote in remotes():
        cmd = "git fetch %s" % remote
        print yellow(cmd)
        call(cmd, shell=True)

