#! /usr/bin/env python

from dev_utils import safeArgs, runCmd, removeArgs
import sys
import os


def usage():
    print """
Usage: git pep8 [-e] [-h]
    Run pep8 against all files staged for commit

    Options:
         -e   Show the commands to be run, but don't run them
         -h   This help message
"""
    return 0


if __name__ == '__main__':

    try:
        args = safeArgs(sys.argv)
        explain = False

        if '-h' in args:
            sys.exit(usage())

        if '-e' in args:
            explain = True

        for line in runCmd("git status --porcelain", capture=True).split('\n'):
            (status, file) = line.split()
            if status.strip() != '??':
                print "--- pep8 %s" % file
                runCmd("pep8 %s" % file, explain=explain)

    except Exception, e:
        print "-- Caught - %s " % e
        sys.exit(-1)
