#! /usr/bin/env python

from subprocess import check_output, call
from optparse import OptionParser
import sys


if __name__ == '__main__':
    usage = "Usage: %prog [-h]"
    description = "run pep8 against all files staged for commit"
    parser = OptionParser(usage=usage, description=description)
    options, args = parser.parse_args()

    for line in check_output("git status -s", shell=True).split('\n'):
        try:
            status, file = line.split()
            if status.strip() != '??':
                print "--- pep8 %s" % file
                call("pep8 %s" % file, shell=True)
        except ValueError:
            pass
