#! /usr/bin/env python

import sys, os

from dev_utils import safeArgs, runCmd

def usage():
    print """
Usage: git un-publish [<remote>] [-e] [-h]
    Remove remote branches

    Example:
        git checkout my-branch
        git un-publish

    Or you can specify the remote branch or origin
        git un-publish origin my-branch
        git un-publish github

    Options:
         -e   Show the commands to be run, but don't run them
         -h   This help message
"""
    return 0


if __name__ == '__main__':

    try:
        args = safeArgs( sys.argv )
        origin = 'origin'
        explain = False

        if '-h' in args:
            sys.exit( usage() )
        
        # If the user specifed a remote repo
        if args[1] != '':
            origin = args[1]

        # Explain the actions taken
        if '-e' in args:
            explain = True

        # Get the current branch from git
        branch = runCmd("git name-rev --name-only HEAD", capture=True).rstrip()
        if branch == '':
            print "-- Could not determine local branch name; not in a git repo?"
            sys.exit(1)

        # If the user specifed a branch
        if args[2] != '':
            branch = args[2]

        # No need to track master
        if branch == 'master':
            print "-- Refusing to un-publish master"
            sys.exit(1)

        # Create the new branch on the remote
        runCmd( "git push %(origin)s :%(branch)s" % locals(), explain=explain )

    except Exception, e:
        print "-- Caught - %s " % e 
        sys.exit(1)

