#! /usr/bin/python

# ---------------------------------------
# For users on a pairing station that both use git
# The script allow you specify what user you want 
# to to preform git actions under
# 
# Example:
#   git as derrick commit -m "This is a commit by derrick"
#   git as nathen commit -m "This is a commit by nathen"
#   git as ryan commit -m "This is a commit by ryan"
#
# Or if you want to change users for all the following commands
#   git as derrick 
#   git commit -m "This is a commit by derrick"
#
# Installation
#   Run the setup.py script in my project 
#   Or
#   Copy this file to a ~/bin directory in your path and the /lib files needed
# ---------------------------------------

import sys, os, ConfigParser

# Add ~/bin/lib to the python search path
sys.path.append( os.path.expanduser("~/bin/lib") )
from utils import safeArgs, quoteArgs, removeArgs, runCmd

try:
    if not os.path.exists( os.path.expanduser("~/.git-users") ):
        print "Please create a ini file called ~/.git-users with the format"
        print "  [user-name] "
        print "  name = FullName"
        print "  email = email@address.com"
        raise Exception("~/.git-users does not exist")

    # Load config file
    config = ConfigParser.ConfigParser()
    config.read( [ os.path.expanduser("~/.git-users") ] )

    args = safeArgs( sys.argv )
    if args[1] == '':
        raise Exception("Please specify a user to preform as")

    if config.get( args[1], 'name' ):
        runCmd( 'git config user.name "%s"' % config.get( args[1], 'name' ) )
        runCmd( 'git config user.email "%s"' % config.get( args[1], 'email' ) )
    else:
        print "-- Unknown user '%s' " % args[1]

    options = quoteArgs( removeArgs( args, [ args[0], args[1], '' ] ) )
    if options == '':
        raise Exception( "Set git user as %s" % config.get( args[1], 'name' ) )
    sys.exit( runCmd( "git %s" % options ) )

except ConfigParser.NoSectionError, e:
    print "-- Config %s" % e 
except Exception, e:
    print "-- %s" % e 
    sys.exit(-1)


    
