# ---------------------
# dev-tools/osx/bash_profile
# ---------------------

alias ssh='ssh -X'

### OSX only ###
# brew install coreutils && brew install git && brew doctor
# Fix the paths by modifying /etc/paths

eval `gdircolors`
alias ls='gls --color=auto'
alias gvim='~/bin/gvim-tabs.py'
