#!/usr/bin/env python

# Script by Derek Monner (http://www.cs.umd.edu/~dmonner)
# Last updated 2012.12.21
#
# This script replaces the iTunes executable. If iTunes would open, such as by pressing
# the "play" media key on your keyboard, and your preferred music player is already open,
# the iTunes program is blocked from launching.
#
# INSTALLATION: 
#
# First, edit this line to make sure the exact, case-sensitive name of your preferred
# music player application is in the list:

apps = ["Spotify", "Songbird", "Banshee", "Clementine"]

# Then, at the terminal, type:
#
# cd /Applications/iTunes.app/Contents/MacOS
# sudo mv iTunes iTunesX
# sudo cp /User/thrawn01/Developement/dev-tools/osx/iTunes iTunes
# sudo chmod 0755 iTunes
#
#
# REMOVAL: To revert to the original behavior, just do:
#
# sudo mv iTunesX iTunes
#

import sys, os, subprocess

launch = True
blocker = ""

ps = subprocess.Popen("/bin/ps -x", shell=True, stdout=subprocess.PIPE)

for line in ps.stdout.read().split("\n"):
    for app in apps:
        if app in line:
            launch = False
            blocker = app

ps.stdout.close()

if launch :
    os.spawnvp(os.P_WAIT, '/Applications/iTunes.app/Contents/MacOS/iTunesX', sys.argv)
else :
    print "Not launching iTunes while %s is running." % blocker
